version: 2
updates:
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    registries:
      - maven-reposilite
registries:
  maven-reposilite:
    type: maven-repository
    url: https://maven.jonasandersen.no/releases
    username: ${{secrets.REPOSILITE_USERNAME}}
    password: ${{secrets.REPOSILITE_PASSWORD}}

