#!/bin/sh

# Initial install
if [ $1 -eq 1 ] ; then
  /usr/bin/systemctl daemon-reload
  /usr/bin/systemctl enable config-server-service.service
fi

# Update
if [ $1 -eq 2 ] ; then
  /usr/bin/systemctl daemon-reload
  /usr/bin/systemctl enable config-server-service.service
fi
