#!/bin/sh

# Initial install
if [ $1 -eq 1 ] ; then
  /usr/bin/getent group runner > /dev/null || /usr/sbin/groupadd --system runner
  /usr/bin/getent passwd runner > /dev/null || /usr/sbin/useradd --system -g runner runner
fi

# Update
if [ $1 -eq 2 ] ; then
  /usr/bin/systemctl daemon-reload
  /usr/bin/systemctl disable config-server-service.service
fi
