spring.datasource.url=${SPRING_CLOUD_CONFIG_JDBC_URL}
spring.datasource.username=${SPRING_CLOUD_CONFIG_JDBC_USERNAME}
spring.datasource.password=${SPRING_CLOUD_CONFIG_JDBC_PASSWORD}
loki.url = http://five.tailscale.svc.cluster.local:3100/loki/api/v1/push